function frase(id, texto, familia, intencoes = ["familia"], extra = {}) {
  return Object.freeze({
    id,
    texto,
    familia,
    intencoes,
    exige: extra.exige || [],
    proibe: extra.proibe || [],
    palavrasContexto: extra.palavrasContexto || [],
    peso: extra.peso || 10,
    ativo: extra.ativo !== false
  });
}

const BANCO_ASSOCIATIVO_V2 = Object.freeze([
  frase("mercado_001", "Boa escolha pra despensa", "mercado"),
  frase("mercado_002", "Item util pra rotina da casa", "mercado"),
  frase("mercado_003", "Vale olhar pra repor em casa", "mercado"),
  frase("bebidas_001", "Boa pedida pra abastecer", "bebidas"),
  frase("bebidas_002", "Boa opcao pra acompanhar a rotina", "bebidas"),
  frase("bebidas_003", "Vale conferir pra garantir a bebida", "bebidas"),
  frase("audio_tv_001", "Som e imagem pedem atencao", "audio_tv"),
  frase("audio_tv_002", "Boa pra melhorar o entretenimento", "audio_tv"),
  frase("audio_tv_003", "Upgrade interessante pra sala", "audio_tv"),
  frase("automotivo_001", "Boa escolha pro carro", "automotivo"),
  frase("automotivo_002", "Essa ajuda nos cuidados automotivos", "automotivo"),
  frase("automotivo_003", "Item util pra deixar no veiculo", "automotivo"),
  frase("bebe_001", "Uma ajudinha dessas na rotina vale ouro", "bebe"),
  frase("bebe_002", "Boa pra facilitar o dia a dia", "bebe"),
  frase("bebe_003", "Cuidado pratico pra rotina do bebe", "bebe"),
  frase("celulares_001", "Boa escolha pra trocar de celular", "celulares"),
  frase("celulares_002", "Upgrade interessante pra conectar melhor", "celulares"),
  frase("celulares_003", "Boa opcao pra rotina conectada", "celulares"),
  frase("computadores_001", "Boa pra trabalhar com mais folego", "computadores"),
  frase("computadores_002", "Upgrade util pro dia a dia", "computadores"),
  frase("computadores_003", "Essa ajuda na produtividade", "computadores"),
  frase("brinquedos_001", "Boa ideia pra alegrar a criançada", "brinquedos"),
  frase("brinquedos_002", "Essa pode render diversao", "brinquedos"),
  frase("brinquedos_003", "Vale conferir pra presentear", "brinquedos"),
  frase("casa_001", "Boa pra facilitar a rotina em casa", "casa"),
  frase("casa_002", "Um upgrade pratico pro lar", "casa"),
  frase("casa_003", "A casa mais organizada agradece", "casa"),
  frase("casa_eletro_001", "Boa escolha pra rotina da casa", "casa_eletro"),
  frase("casa_eletro_002", "Essa ajuda nas tarefas do dia", "casa_eletro"),
  frase("casa_eletro_003", "Praticidade extra pra casa", "casa_eletro"),
  frase("cozinha_001", "Cozinha pratica agradece", "cozinha_pratica", ["familia"], { palavrasContexto: ["cozinha"] }),
  frase("cozinha_002", "Boa pra agilizar a cozinha", "cozinha_pratica", ["familia"], { palavrasContexto: ["cozinha"] }),
  frase("cozinha_003", "Essa facilita o preparo do dia", "cozinha_pratica", ["familia"], { palavrasContexto: ["cozinha"] }),
  frase("ferramentas_001", "Boa pra completar a caixa", "ferramentas"),
  frase("ferramentas_002", "Ferramenta util sempre ajuda", "ferramentas"),
  frase("ferramentas_003", "Essa resolve muita coisa em casa", "ferramentas"),
  frase("limpeza_001", "Boa pra deixar tudo em ordem", "limpeza"),
  frase("limpeza_002", "Rotina de limpeza mais pratica", "limpeza"),
  frase("limpeza_003", "Essa ajuda na faxina do dia", "limpeza"),
  frase("eletronicos_001", "Tecnologia util pro dia a dia", "eletronicos"),
  frase("eletronicos_002", "Essa deixa a rotina mais esperta", "eletronicos"),
  frase("eletronicos_003", "Boa pra modernizar a rotina", "eletronicos"),
  frase("perifericos_001", "Setup mais completo com essa", "perifericos"),
  frase("perifericos_002", "Boa pra melhorar os acessorios", "perifericos"),
  frase("perifericos_003", "Detalhe que faz diferenca no setup", "perifericos"),
  frase("moda_001", "Boa escolha pra renovar o visual", "moda"),
  frase("moda_002", "Essa combina com o guarda roupa", "moda"),
  frase("moda_003", "Visual do dia agradece", "moda"),
  frase("calcados_001", "Boa pedida pros pes", "calcados"),
  frase("calcados_002", "Conforto tambem entra na conta", "calcados"),
  frase("calcados_003", "Essa combina com a rotina", "calcados"),
  frase("gamer_001", "Upgrade interessante pro setup", "gamer"),
  frase("gamer_002", "Seu setup merece atencao", "gamer"),
  frase("gamer_003", "Boa pra deixar o setup no jeito", "gamer"),
  frase("infantil_001", "Boa escolha pros pequenos", "infantil"),
  frase("infantil_002", "Essa ajuda na rotina infantil", "infantil"),
  frase("infantil_003", "Vale conferir pra criançada", "infantil"),
  frase("pet_001", "Boa escolha pra rotina pet", "pet"),
  frase("pet_002", "Boa pra cuidar do companheiro", "pet"),
  frase("pet_003", "Essa ajuda na rotina pet", "pet"),
  frase("beleza_001", "Uma ajudinha dessas na rotina cai bem", "beleza"),
  frase("beleza_002", "Boa pra cuidar do visual", "beleza"),
  frase("beleza_003", "Rotina de beleza agradece", "beleza"),
  frase("esporte_001", "Boa pra manter o ritmo", "esporte"),
  frase("esporte_002", "Essa combina com treino em dia", "esporte"),
  frase("esporte_003", "Vale conferir pra rotina ativa", "esporte"),
  frase("pesca_001", "Boa pedida pra proxima pescaria", "pesca_camping", ["familia"], { palavrasContexto: ["pesca"] }),
  frase("pesca_002", "Essa combina com aventura ao ar livre", "pesca_camping"),
  frase("pesca_003", "Item util pra camping e pesca", "pesca_camping"),
  frase("games_001", "Boa pra jogar com mais conforto", "games"),
  frase("games_002", "Essa combina com a jogatina", "games"),
  frase("games_003", "Upgrade interessante pra diversao", "games"),
  frase("climatizacao_001", "Conforto termico tambem importa", "climatizacao"),
  frase("climatizacao_002", "Boa pra deixar o ambiente melhor", "climatizacao"),
  frase("climatizacao_003", "Boa pra reforcar o conforto do ambiente", "climatizacao"),
  frase("iluminacao_001", "Boa pra melhorar o ambiente", "iluminacao"),
  frase("iluminacao_002", "Iluminacao certa muda tudo", "iluminacao"),
  frase("iluminacao_003", "Essa ajuda no projeto da casa", "iluminacao"),
  frase("cabelo_001", "Cabelo em dia com mais praticidade", "beleza", ["familia"], { palavrasContexto: ["cabelo"] }),
  frase("cabelo_002", "Boa pra rotina dos fios", "beleza", ["familia"], { palavrasContexto: ["cabelo"] }),
  frase("setup_001", "Boa pra ajustar o setup", "gamer", ["familia"], { palavrasContexto: ["setup"] }),
  frase("setup_002", "Setup mais esperto com essa", "perifericos", ["familia"], { palavrasContexto: ["setup"] }),
  frase("limpeza_pratica_001", "Limpeza mais pratica no dia a dia", "limpeza", ["familia"], { palavrasContexto: ["limpeza_pratica"] }),
  frase("limpeza_pratica_002", "Boa pra simplificar a faxina", "casa_eletro", ["familia"], { palavrasContexto: ["limpeza_pratica"] }),

  frase("oportunidade_001", "Opa, olha essa", "oportunidade", ["oportunidade"]),
  frase("oportunidade_002", "Essa merece uma conferida", "oportunidade", ["oportunidade"]),
  frase("oportunidade_003", "Boa oportunidade pra olhar com calma", "oportunidade", ["oportunidade"]),
  frase("oportunidade_004", "Essa chamou atencao por aqui", "oportunidade", ["oportunidade"]),
  frase("oportunidade_005", "Vale conferir essa opcao", "oportunidade", ["oportunidade"]),
  frase("oportunidade_006", "Olha essa sugestao interessante", "oportunidade", ["oportunidade"]),
  frase("oportunidade_007", "Boa pra colocar no radar", "oportunidade", ["oportunidade"]),
  frase("oportunidade_008", "Essa pode fazer sentido", "oportunidade", ["oportunidade"]),
  frase("oportunidade_009", "Achado interessante pra conferir", "oportunidade", ["oportunidade"]),
  frase("oportunidade_010", "Essa vale uma olhada", "oportunidade", ["oportunidade"]),
  frase("oportunidade_011", "Boa opcao pra avaliar", "oportunidade", ["oportunidade"]),
  frase("oportunidade_012", "Olha essa possibilidade", "oportunidade", ["oportunidade"]),

  frase("cupom_001", "🔥 Tem cupom nessa oferta", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_002", "💰 Oferta boa e com cupom", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_003", "🤑 Opa, essa tem cupom", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_004", "🎟️ Tem cupom pra aproveitar", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_005", "💸 Achamos cupom por aqui", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_006", "👀 Opa, olha o cupom", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_007", "🏷️ Essa vem com cupom", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_008", "🔥 Cupom na area", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_009", "🎟️ Tem cupom esperando aqui", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_010", "💰 Essa oferta traz cupom", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_011", "👀 Cupom confirmado nessa", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_012", "💸 Cupom liberado pra conferir", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_013", "🎟️ Essa tem cupom ativo", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_014", "🔥 Oferta com cupom disponivel", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_015", "💰 Cupom junto nessa oferta", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_016", "👀 Tem cupom nessa aqui", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_017", "🏷️ Cupom encontrado nessa", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_018", "🎟️ Cupom pronto pra usar", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_019", "💸 Essa veio com cupom", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_020", "🔥 Cupom confirmado por aqui", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("resgate_001", "⭐ Tem beneficio pra resgatar", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_002", "🎁 Essa oferta tem resgate", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_003", "👀 Opa, tem resgate por aqui", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_004", "🏆 Oferta com resgate disponivel", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_005", "🎯 Beneficio esperando resgate", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_006", "✨ Essa traz opcao de resgate", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_007", "🔐 Encontramos resgate nessa", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_008", "⭐ Resgate confirmado pra conferir", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_009", "🎁 Tem resgate nessa oferta", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_010", "👀 Resgate disponivel por aqui", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_011", "🎯 Essa veio com resgate", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_012", "✨ Beneficio pra resgatar nessa", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_013", "🏆 Resgate junto da oferta", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_014", "⭐ Boa pra conferir o resgate", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_015", "🎁 Resgate encontrado nessa", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_016", "👀 Tem beneficio pra resgatar", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_017", "🔐 Resgate validado pra oferta", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_018", "✨ Oferta trazendo resgate", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_019", "🎯 Resgate pronto pra conferir", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_020", "⭐ Essa inclui resgate", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("beneficio_001", "✨ Essa veio com beneficio real", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_002", "⭐ Beneficio confirmado pra conferir", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_003", "🎁 Oferta com beneficio confirmado", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_004", "👀 Tem beneficio nessa oferta", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_005", "🎯 Beneficio real por aqui", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_006", "✨ Essa traz beneficio extra", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_007", "⭐ Beneficio detectado nessa", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_008", "🎁 Boa pra conferir o beneficio", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_009", "👀 Beneficio disponivel na oferta", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_010", "🎯 Oferta com beneficio real", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_011", "✨ Beneficio extra confirmado", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_012", "⭐ Essa inclui beneficio", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("economia_001", "💰 Boa oportunidade pra economizar", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_002", "💸 Essa chamou atencao pela economia", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_003", "👀 Economia confirmada nessa", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_004", "🏷️ Oferta com economia oficial", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_005", "💰 Boa pra economizar nessa", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_006", "💸 Essa veio com economia", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_007", "👀 Desconto oficial por aqui", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_008", "🏷️ Economia validada nessa oferta", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_009", "💰 Vale olhar pela economia", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_010", "💸 Oferta trazendo economia", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_011", "👀 Essa tem economia oficial", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_012", "🏷️ Economia junto da oferta", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_013", "💰 Economia boa pra conferir", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_014", "💸 Essa ajuda a economizar", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_015", "👀 Desconto confirmado nessa", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("frete_001", "🚚 Frete gratis ajuda bastante", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_002", "📦 Com frete gratis fica melhor", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_003", "👀 Frete gratis confirmado", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_004", "🚚 Essa veio com frete gratis", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_005", "📦 Oferta com frete gratis", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_006", "✨ Frete gratis por aqui", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_007", "🚚 Frete gratis nessa oferta", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_008", "📦 Boa com frete gratis", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_009", "👀 Frete gratis disponivel", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_010", "🚚 Essa inclui frete gratis", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_011", "📦 Frete gratis pra conferir", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_012", "✨ Oferta trazendo frete gratis", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("parcelamento_001", "💳 Parcelamento ajuda no planejamento", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_002", "🧾 Boa pra pagar com mais folego", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_003", "💳 Essa tem parcelamento", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_004", "👀 Parcelamento disponivel nessa", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_005", "🧾 Oferta com parcelamento", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_006", "💳 Parcelamento confirmado aqui", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_007", "👀 Essa veio com parcelamento", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_008", "🧾 Boa pra parcelar a compra", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_009", "💳 Parcelamento pra conferir", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_010", "👀 Tem parcelamento nessa oferta", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("cupom_gamer_001", "Cupom bom pro setup", "gamer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_casa_001", "Cupom util pra casa", "casa", ["cupom"], { exige: ["cupom"] }),
  frase("resgate_shopee_001", "Resgate interessante pra conferir", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("beneficio_pet_001", "Beneficio bom pra rotina pet", "pet", ["beneficio"], { exige: ["beneficio"] }),
  frase("economia_moda_001", "Economia boa pra renovar o visual", "moda", ["economia"], { exige: ["desconto"] }),
  frase("frete_casa_001", "Frete gratis ajuda na casa", "casa", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("parcelamento_eletro_001", "Parcelamento combina com eletro", "casa_eletro", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("beneficio_beleza_001", "Beneficio bom pra rotina de beleza", "beleza", ["beneficio"], { exige: ["beneficio"] }),
  frase("economia_ferramentas_001", "Economia boa pra completar a caixa", "ferramentas", ["economia"], { exige: ["desconto"] }),
  frase("frete_calcados_001", "Frete gratis ajuda no calcado", "calcados", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("parcelamento_computadores_001", "Parcelamento ajuda no upgrade", "computadores", ["parcelamento"], { exige: ["parcelamento"] })
]);

module.exports = {
  BANCO_ASSOCIATIVO_V2
};
