function frase(id, texto, familia, intencoes = ["familia"], extra = {}) {
  return Object.freeze({
    id,
    texto,
    familia,
    intencoes,
    exige: extra.exige || [],
    proibe: extra.proibe || [],
    palavrasContexto: extra.palavrasContexto || [],
    tom: extra.tom || "",
    eixo: extra.eixo || "",
    peso: extra.peso || 10,
    ativo: extra.ativo !== false
  });
}

const BANCO_ASSOCIATIVO_V2_BASE = Object.freeze([
  frase("mercado_001", "Boa escolha pra despensa", "mercado"),
  frase("mercado_002", "Item util pra rotina da casa", "mercado"),
  frase("mercado_003", "Vale olhar pra repor em casa", "mercado"),
  frase("bebidas_001", "Boa pedida pra abastecer", "bebidas"),
  frase("bebidas_002", "Boa opcao pra acompanhar a rotina", "bebidas"),
  frase("bebidas_003", "Vale conferir pra garantir a bebida", "bebidas"),
  frase("audio_tv_001", "Som e imagem pedem atencao", "audio_tv"),
  frase("audio_tv_002", "Boa pra melhorar o entretenimento", "audio_tv"),
  frase("audio_tv_003", "Upgrade interessante pra sala", "audio_tv"),
  frase("automotivo_001", "Boa escolha pro carro", "automotivo"),
  frase("automotivo_002", "Essa ajuda nos cuidados automotivos", "automotivo"),
  frase("automotivo_003", "Item util pra deixar no veiculo", "automotivo"),
  frase("bebe_001", "Uma ajudinha dessas na rotina vale ouro", "bebe"),
  frase("bebe_002", "Boa pra facilitar o dia a dia", "bebe"),
  frase("bebe_003", "Cuidado pratico pra rotina do bebe", "bebe"),
  frase("celulares_001", "Boa escolha pra trocar de celular", "celulares"),
  frase("celulares_002", "Upgrade interessante pra conectar melhor", "celulares"),
  frase("celulares_003", "Boa opcao pra rotina conectada", "celulares"),
  frase("computadores_001", "Boa pra trabalhar com mais folego", "computadores"),
  frase("computadores_002", "Upgrade util pro dia a dia", "computadores"),
  frase("computadores_003", "Essa ajuda na produtividade", "computadores"),
  frase("brinquedos_001", "Boa ideia pra alegrar a criançada", "brinquedos"),
  frase("brinquedos_002", "Essa pode render diversao", "brinquedos"),
  frase("brinquedos_003", "Vale conferir pra presentear", "brinquedos"),
  frase("casa_001", "Boa pra facilitar a rotina em casa", "casa"),
  frase("casa_002", "Um upgrade pratico pro lar", "casa"),
  frase("casa_003", "A casa mais organizada agradece", "casa"),
  frase("casa_eletro_001", "Boa escolha pra rotina da casa", "casa_eletro"),
  frase("casa_eletro_002", "Essa ajuda nas tarefas do dia", "casa_eletro"),
  frase("casa_eletro_003", "Praticidade extra pra casa", "casa_eletro"),
  frase("cozinha_001", "Cozinha pratica agradece", "cozinha_pratica", ["familia"], { palavrasContexto: ["cozinha"] }),
  frase("cozinha_002", "Boa pra agilizar a cozinha", "cozinha_pratica", ["familia"], { palavrasContexto: ["cozinha"] }),
  frase("cozinha_003", "Essa facilita o preparo do dia", "cozinha_pratica", ["familia"], { palavrasContexto: ["cozinha"] }),
  frase("ferramentas_001", "Boa pra completar a caixa", "ferramentas"),
  frase("ferramentas_002", "Ferramenta util sempre ajuda", "ferramentas"),
  frase("ferramentas_003", "Essa resolve muita coisa em casa", "ferramentas"),
  frase("limpeza_001", "Boa pra deixar tudo em ordem", "limpeza"),
  frase("limpeza_002", "Rotina de limpeza mais pratica", "limpeza"),
  frase("limpeza_003", "Essa ajuda na faxina do dia", "limpeza"),
  frase("eletronicos_001", "Tecnologia util pro dia a dia", "eletronicos"),
  frase("eletronicos_002", "Essa deixa a rotina mais esperta", "eletronicos"),
  frase("eletronicos_003", "Boa pra modernizar a rotina", "eletronicos"),
  frase("perifericos_001", "Setup mais completo com essa", "perifericos"),
  frase("perifericos_002", "Boa pra melhorar os acessorios", "perifericos"),
  frase("perifericos_003", "Detalhe que faz diferenca no setup", "perifericos"),
  frase("moda_001", "Boa escolha pra renovar o visual", "moda"),
  frase("moda_002", "Essa combina com o guarda roupa", "moda"),
  frase("moda_003", "Visual do dia agradece", "moda"),
  frase("calcados_001", "Boa pedida pros pes", "calcados"),
  frase("calcados_002", "Conforto tambem entra na conta", "calcados"),
  frase("calcados_003", "Essa combina com a rotina", "calcados"),
  frase("gamer_001", "Upgrade interessante pro setup", "gamer"),
  frase("gamer_002", "Seu setup merece atencao", "gamer"),
  frase("gamer_003", "Boa pra deixar o setup no jeito", "gamer"),
  frase("infantil_001", "Boa escolha pros pequenos", "infantil"),
  frase("infantil_002", "Essa ajuda na rotina infantil", "infantil"),
  frase("infantil_003", "Vale conferir pra criançada", "infantil"),
  frase("pet_001", "Boa escolha pra rotina pet", "pet"),
  frase("pet_002", "Boa pra cuidar do companheiro", "pet"),
  frase("pet_003", "Essa ajuda na rotina pet", "pet"),
  frase("beleza_001", "Uma ajudinha dessas na rotina cai bem", "beleza"),
  frase("beleza_002", "Boa pra cuidar do visual", "beleza"),
  frase("beleza_003", "Rotina de beleza agradece", "beleza"),
  frase("esporte_001", "Boa pra manter o ritmo", "esporte"),
  frase("esporte_002", "Essa combina com treino em dia", "esporte"),
  frase("esporte_003", "Vale conferir pra rotina ativa", "esporte"),
  frase("pesca_001", "Boa pedida pra proxima pescaria", "pesca_camping", ["familia"], { palavrasContexto: ["pesca"] }),
  frase("pesca_002", "Essa combina com aventura ao ar livre", "pesca_camping"),
  frase("pesca_003", "Item util pra camping e pesca", "pesca_camping"),
  frase("games_001", "Boa pra jogar com mais conforto", "games"),
  frase("games_002", "Essa combina com a jogatina", "games"),
  frase("games_003", "Upgrade interessante pra diversao", "games"),
  frase("climatizacao_001", "Conforto termico tambem importa", "climatizacao"),
  frase("climatizacao_002", "Boa pra deixar o ambiente melhor", "climatizacao"),
  frase("climatizacao_003", "Boa pra reforcar o conforto do ambiente", "climatizacao"),
  frase("iluminacao_001", "Boa pra melhorar o ambiente", "iluminacao"),
  frase("iluminacao_002", "Iluminacao certa muda tudo", "iluminacao"),
  frase("iluminacao_003", "Essa ajuda no projeto da casa", "iluminacao"),
  frase("cabelo_001", "Cabelo em dia com mais praticidade", "beleza", ["familia"], { palavrasContexto: ["cabelo"] }),
  frase("cabelo_002", "Boa pra rotina dos fios", "beleza", ["familia"], { palavrasContexto: ["cabelo"] }),
  frase("setup_001", "Boa pra ajustar o setup", "gamer", ["familia"], { palavrasContexto: ["setup"] }),
  frase("setup_002", "Setup mais esperto com essa", "perifericos", ["familia"], { palavrasContexto: ["setup"] }),
  frase("limpeza_pratica_001", "Limpeza mais pratica no dia a dia", "limpeza", ["familia"], { palavrasContexto: ["limpeza_pratica"] }),
  frase("limpeza_pratica_002", "Boa pra simplificar a faxina", "casa_eletro", ["familia"], { palavrasContexto: ["limpeza_pratica"] }),

  frase("oportunidade_001", "Opa, olha essa", "oportunidade", ["oportunidade"]),
  frase("oportunidade_002", "Essa merece uma conferida", "oportunidade", ["oportunidade"]),
  frase("oportunidade_003", "Boa oportunidade pra olhar com calma", "oportunidade", ["oportunidade"]),
  frase("oportunidade_004", "Essa chamou atencao por aqui", "oportunidade", ["oportunidade"]),
  frase("oportunidade_005", "Vale conferir essa opcao", "oportunidade", ["oportunidade"]),
  frase("oportunidade_006", "Olha essa sugestao interessante", "oportunidade", ["oportunidade"]),
  frase("oportunidade_007", "Boa pra colocar no radar", "oportunidade", ["oportunidade"]),
  frase("oportunidade_008", "Essa pode fazer sentido", "oportunidade", ["oportunidade"]),
  frase("oportunidade_009", "Achado interessante pra conferir", "oportunidade", ["oportunidade"]),
  frase("oportunidade_010", "Essa vale uma olhada", "oportunidade", ["oportunidade"]),
  frase("oportunidade_011", "Boa opcao pra avaliar", "oportunidade", ["oportunidade"]),
  frase("oportunidade_012", "Olha essa possibilidade", "oportunidade", ["oportunidade"]),

  frase("cupom_001", "🔥 Tem cupom nessa oferta", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_002", "💰 Oferta boa e com cupom", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_003", "🤑 Opa, essa tem cupom", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_004", "🎟️ Tem cupom pra aproveitar", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_005", "💸 Achamos cupom por aqui", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_006", "👀 Opa, olha o cupom", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_007", "🏷️ Essa vem com cupom", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_008", "🔥 Cupom na area", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_009", "🎟️ Tem cupom esperando aqui", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_010", "💰 Essa oferta traz cupom", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_011", "👀 Cupom confirmado nessa", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_012", "💸 Cupom liberado pra conferir", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_013", "🎟️ Essa tem cupom ativo", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_014", "🔥 Oferta com cupom disponivel", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_015", "💰 Cupom junto nessa oferta", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_016", "👀 Tem cupom nessa aqui", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_017", "🏷️ Cupom encontrado nessa", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_018", "🎟️ Cupom pronto pra usar", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_019", "💸 Essa veio com cupom", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_020", "🔥 Cupom confirmado por aqui", "qualquer", ["cupom"], { exige: ["cupom"] }),
  frase("resgate_001", "⭐ Tem beneficio pra resgatar", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_002", "🎁 Essa oferta tem resgate", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_003", "👀 Opa, tem resgate por aqui", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_004", "🏆 Oferta com resgate disponivel", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_005", "🎯 Beneficio esperando resgate", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_006", "✨ Essa traz opcao de resgate", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_007", "🔐 Encontramos resgate nessa", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_008", "⭐ Resgate confirmado pra conferir", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_009", "🎁 Tem resgate nessa oferta", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_010", "👀 Resgate disponivel por aqui", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_011", "🎯 Essa veio com resgate", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_012", "✨ Beneficio pra resgatar nessa", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_013", "🏆 Resgate junto da oferta", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_014", "⭐ Boa pra conferir o resgate", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_015", "🎁 Resgate encontrado nessa", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_016", "👀 Tem beneficio pra resgatar", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_017", "🔐 Resgate validado pra oferta", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_018", "✨ Oferta trazendo resgate", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_019", "🎯 Resgate pronto pra conferir", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("resgate_020", "⭐ Essa inclui resgate", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("beneficio_001", "✨ Essa veio com beneficio real", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_002", "⭐ Beneficio confirmado pra conferir", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_003", "🎁 Oferta com beneficio confirmado", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_004", "👀 Tem beneficio nessa oferta", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_005", "🎯 Beneficio real por aqui", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_006", "✨ Essa traz beneficio extra", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_007", "⭐ Beneficio detectado nessa", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_008", "🎁 Boa pra conferir o beneficio", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_009", "👀 Beneficio disponivel na oferta", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_010", "🎯 Oferta com beneficio real", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_011", "✨ Beneficio extra confirmado", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("beneficio_012", "⭐ Essa inclui beneficio", "qualquer", ["beneficio"], { exige: ["beneficio"] }),
  frase("economia_001", "💰 Boa oportunidade pra economizar", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_002", "💸 Essa chamou atencao pela economia", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_003", "👀 Economia confirmada nessa", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_004", "🏷️ Oferta com economia oficial", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_005", "💰 Boa pra economizar nessa", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_006", "💸 Essa veio com economia", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_007", "👀 Desconto oficial por aqui", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_008", "🏷️ Economia validada nessa oferta", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_009", "💰 Vale olhar pela economia", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_010", "💸 Oferta trazendo economia", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_011", "👀 Essa tem economia oficial", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_012", "🏷️ Economia junto da oferta", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_013", "💰 Economia boa pra conferir", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_014", "💸 Essa ajuda a economizar", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("economia_015", "👀 Desconto confirmado nessa", "qualquer", ["economia"], { exige: ["desconto"] }),
  frase("frete_001", "🚚 Frete gratis ajuda bastante", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_002", "📦 Com frete gratis fica melhor", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_003", "👀 Frete gratis confirmado", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_004", "🚚 Essa veio com frete gratis", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_005", "📦 Oferta com frete gratis", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_006", "✨ Frete gratis por aqui", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_007", "🚚 Frete gratis nessa oferta", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_008", "📦 Boa com frete gratis", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_009", "👀 Frete gratis disponivel", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_010", "🚚 Essa inclui frete gratis", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_011", "📦 Frete gratis pra conferir", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("frete_012", "✨ Oferta trazendo frete gratis", "qualquer", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("parcelamento_001", "💳 Parcelamento ajuda no planejamento", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_002", "🧾 Boa pra pagar com mais folego", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_003", "💳 Essa tem parcelamento", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_004", "👀 Parcelamento disponivel nessa", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_005", "🧾 Oferta com parcelamento", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_006", "💳 Parcelamento confirmado aqui", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_007", "👀 Essa veio com parcelamento", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_008", "🧾 Boa pra parcelar a compra", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_009", "💳 Parcelamento pra conferir", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("parcelamento_010", "👀 Tem parcelamento nessa oferta", "qualquer", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("cupom_gamer_001", "Cupom bom pro setup", "gamer", ["cupom"], { exige: ["cupom"] }),
  frase("cupom_casa_001", "Cupom util pra casa", "casa", ["cupom"], { exige: ["cupom"] }),
  frase("resgate_shopee_001", "Resgate interessante pra conferir", "qualquer", ["resgate"], { exige: ["resgate"] }),
  frase("beneficio_pet_001", "Beneficio bom pra rotina pet", "pet", ["beneficio"], { exige: ["beneficio"] }),
  frase("economia_moda_001", "Economia boa pra renovar o visual", "moda", ["economia"], { exige: ["desconto"] }),
  frase("frete_casa_001", "Frete gratis ajuda na casa", "casa", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("parcelamento_eletro_001", "Parcelamento combina com eletro", "casa_eletro", ["parcelamento"], { exige: ["parcelamento"] }),
  frase("beneficio_beleza_001", "Beneficio bom pra rotina de beleza", "beleza", ["beneficio"], { exige: ["beneficio"] }),
  frase("economia_ferramentas_001", "Economia boa pra completar a caixa", "ferramentas", ["economia"], { exige: ["desconto"] }),
  frase("frete_calcados_001", "Frete gratis ajuda no calcado", "calcados", ["frete_gratis"], { exige: ["freteGratis"] }),
  frase("parcelamento_computadores_001", "Parcelamento ajuda no upgrade", "computadores", ["parcelamento"], { exige: ["parcelamento"] })
]);

const EIXOS_CURADORIA_V21 = Object.freeze([
  "descoberta",
  "cotidiano",
  "praticidade",
  "desejo",
  "renovacao",
  "oportunidade"
]);

function tomCuradoria(textoFrase) {
  const totalPalavras = String(textoFrase || "").trim().split(/\s+/).filter(Boolean).length;
  return totalPalavras <= 8 ? "curta" : "media";
}

function frasesCuradasV21(prefixo, familia, textos, intencoes = ["familia"]) {
  return textos.map((textoFrase, index) => {
    const tom = tomCuradoria(textoFrase);
    return frase(
      `${prefixo}_v21_${String(index + 1).padStart(3, "0")}`,
      textoFrase,
      familia,
      intencoes,
      { tom, eixo: EIXOS_CURADORIA_V21[index % EIXOS_CURADORIA_V21.length], peso: tom === "curta" ? 8 : 11 }
    );
  });
}

const EXPANSAO_HUMANA_V21 = Object.freeze([
  ...frasesCuradasV21("audio_tv", "audio_tv", [
    "📺 Boa para renovar a sala.",
    "Som e imagem também merecem cuidado.",
    "Cinema em casa começa nos detalhes.",
    "Boa ideia para deixar o momento de assistir mais gostoso.",
    "Entretenimento da sala ganha força com o item certo.",
    "Para quem vive no sofá vendo série, vale conferir.",
    "A sessão de filmes pode ficar mais completa por aqui.",
    "Um upgrade simples pode melhorar a hora de assistir.",
    "Para quem gosta de maratonar, essa merece entrar no radar.",
    "Uma novidade dessas combina com sala mais completa.",
    "Áudio e imagem fazem diferença na hora de relaxar.",
    "Pode ser aquele detalhe que melhora o momento de assistir.",
    "Para deixar a TV mais presente na rotina, vale conferir.",
    "Quem curte música e filmes sabe que acessórios ajudam bastante.",
    "A sala fica mais interessante quando o entretenimento acompanha.",
    "Essa conversa bem com quem gosta de som e imagem em dia.",
    "Vale olhar com calma se a ideia é melhorar o cantinho da TV.",
    "Uma escolha simples pode deixar a sessão mais gostosa.",
    "Para ouvir melhor, assistir melhor e aproveitar mais.",
    "Tem novidade boa para quem cuida do entretenimento em casa.",
    "Esse tipo de item costuma deixar a experiência mais prática.",
    "Boa para quem quer uma sala mais pronta para receber.",
    "Um detalhe certo pode mudar a forma de curtir filmes.",
    "Para quem vive de playlist e série, fica a dica.",
    "Entre sofá, TV e som, essa pode fazer sentido."
  ]),
  ...frasesCuradasV21("automotivo", "automotivo", [
    "🚗 Boa para cuidar do carro.",
    "Um item útil para deixar o veículo mais preparado.",
    "Garagem organizada facilita quando aparece algum cuidado no carro.",
    "Para quem pega estrada, alguns detalhes fazem diferença.",
    "A rotina automotiva fica melhor com soluções simples.",
    "Vale conferir para cuidar melhor do carro no dia a dia.",
    "Boa para completar o porta-malas.",
    "Cuidado automotivo sem complicar.",
    "Para quem gosta de manter o carro em ordem, vale conferir.",
    "Uma solução prática pode facilitar bastante a rotina no volante.",
    "Tem item que faz sentido ter sempre à mão no veículo.",
    "Quem pega estrada sabe como alguns acessórios ajudam.",
    "Uma novidade para deixar os cuidados do carro mais simples.",
    "Para organizar melhor a rotina automotiva, essa merece atenção.",
    "Pequenos cuidados no carro deixam a rotina mais tranquila.",
    "Boa opção para quem gosta de preparar tudo antes de sair.",
    "Se o assunto é carro no dia a dia, vale dar uma olhada.",
    "Essa combina com quem cuida do veículo sem enrolação.",
    "Pode ser útil para deixar a garagem mais completa.",
    "Para quem vive entre cidade e estrada, fica no radar.",
    "Um acessório certo pode deixar o uso do carro mais tranquilo.",
    "Vale conferir se a ideia é facilitar cuidados automotivos.",
    "Tem novidade boa para quem gosta do carro sempre pronto.",
    "A rotina com o veículo fica melhor com itens certos.",
    "Para o próximo cuidado no carro, essa pode ajudar."
  ]),
  ...frasesCuradasV21("bebe", "bebe", [
    "👶 Boa para a rotina do bebê.",
    "Cuidado diário com o bebê fica melhor quando tudo ajuda.",
    "Pequenos cuidados contam muito na rotina dos primeiros anos.",
    "Para deixar a família mais preparada, vale conferir.",
    "Rotina do bebê mais tranquila.",
    "Boa para manter por perto nos momentos de cuidado.",
    "Uma ajuda simples pode deixar o dia a dia mais leve.",
    "Vale olhar se a rotina com bebê anda corrida.",
    "Quem cuida de bebê sabe como praticidade ajuda.",
    "Uma novidade dessas pode facilitar pequenos momentos da rotina.",
    "Para deixar o cuidado diário mais organizado, vale conferir.",
    "Tem coisa que ajuda bastante quando a rotina está corrida.",
    "A família agradece quando o cuidado fica mais simples.",
    "Uma opção prática para acompanhar o dia a dia dos pequenos.",
    "Para quem está montando o enxoval, essa merece atenção.",
    "Cuidado com bebê pede itens funcionais e fáceis de usar.",
    "Vale colocar no radar para a rotina dos primeiros anos.",
    "Pequenos detalhes podem deixar o cuidado mais leve.",
    "Essa combina com quem gosta de deixar tudo preparado.",
    "Para trocar, organizar ou cuidar, praticidade sempre ajuda.",
    "Boa alternativa para quem busca algo útil para os pequenos.",
    "A rotina da casa muda, e algumas ajudas fazem diferença.",
    "Pode ser uma escolha boa para presentear famílias com bebê.",
    "Para o dia a dia dos pequenos, vale uma conferida.",
    "Um item simples pode trazer mais ordem para a rotina."
  ]),
  ...frasesCuradasV21("bebidas", "bebidas", [
    "🥤 Boa para abastecer a rotina.",
    "Geladeira bem abastecida muda a pausa do dia.",
    "Para deixar a próxima pausa mais gostosa, vale conferir.",
    "Vale conferir antes de perceber que precisa repor.",
    "A bebida certa deixa alguns momentos mais práticos.",
    "Boa para manter na geladeira e facilitar a rotina.",
    "Pausa do dia mais gostosa.",
    "Combina com a geladeira cheia.",
    "Para quem gosta de manter bebidas por perto, vale conferir.",
    "Uma opção dessas pode ajudar na próxima compra da casa.",
    "Tem bebida que combina com descanso, almoço ou encontro simples.",
    "Boa escolha para repor antes de perceber que acabou.",
    "Para deixar a despensa mais completa, essa merece atenção.",
    "Quem organiza a semana sabe que bebida também entra na lista.",
    "Uma novidade para acompanhar melhor os momentos de pausa.",
    "Vale colocar no radar para a próxima ida ao mercado.",
    "Boa para quem gosta de receber sem improvisar tudo na hora.",
    "A rotina fica mais fácil quando a geladeira está preparada.",
    "Para completar a lista de casa, essa pode fazer sentido.",
    "Tem opção que combina bem com o dia a dia.",
    "Se a ideia é abastecer com calma, vale dar uma olhada.",
    "Uma bebida a mais sempre ajuda nos encontros de casa.",
    "Boa para quem gosta de deixar tudo pronto para a semana.",
    "Essa pode entrar fácil na lista da próxima compra.",
    "Para pausa, almoço ou visita, vale conferir."
  ]),
  ...frasesCuradasV21("beleza", "beleza", [
    "💄 Boa para renovar o cuidado.",
    "Autocuidado também merece espaço na rotina corrida.",
    "A necessaire sempre ganha vida com novidades úteis.",
    "Para variar o cuidado com o visual, vale conferir.",
    "Rotina de beleza mais prática.",
    "Vale olhar sem pressa para renovar o cuidado.",
    "O cuidado diário fica melhor com escolhas bem pensadas.",
    "Beleza sem complicar demais combina com rotina real.",
    "Para quem gosta de se cuidar, essa merece entrar no radar.",
    "Uma novidade dessas combina com o momento de autocuidado.",
    "Pode ser aquele item que faltava na rotina de beleza.",
    "Quem monta uma necessaire prática sabe valorizar boas escolhas.",
    "Para renovar o cuidado sem exagero, vale conferir.",
    "Tem produto que deixa o cuidado diário mais simples.",
    "Uma escolha interessante para variar a rotina de beleza.",
    "Vale colocar na lista de quem gosta de testar novidades.",
    "Autocuidado fica melhor quando o item combina com a rotina.",
    "Para cabelo, pele ou visual, essa pode fazer sentido.",
    "Boa opção para deixar o cuidado mais organizado.",
    "Uma dica para quem gosta de praticidade no cuidado pessoal.",
    "Essa conversa com quem separa um tempo para si.",
    "Para atualizar a rotina de beleza, vale uma conferida.",
    "Pequenos itens podem mudar o jeito de se cuidar.",
    "Tem novidade boa para quem acompanha beleza de perto.",
    "Uma opção versátil para entrar no cuidado do dia."
  ]),
  ...frasesCuradasV21("brinquedos", "brinquedos", [
    "🧸 Uma boa ideia para renovar a hora de brincar.",
    "Diversão também merece novidade de vez em quando.",
    "Para presentear sem cair no repetido, vale conferir.",
    "Pode render bons momentos na rotina dos pequenos.",
    "Brincadeira nova chama atenção quando tem imaginação.",
    "Vale olhar para surpreender os pequenos com algo diferente.",
    "Presente simples e divertido.",
    "Hora de brincar agradece.",
    "Para quem procura algo para criança, vale conferir.",
    "Uma novidade dessas pode animar a rotina dos pequenos.",
    "Brinquedo bom é aquele que rende história depois.",
    "Pode ser uma escolha legal para presentear sem complicar.",
    "Para variar a brincadeira em casa, essa merece atenção.",
    "Quem tem criança por perto sabe como novidade faz sucesso.",
    "Uma opção para deixar o tempo livre mais divertido.",
    "Vale colocar no radar antes da próxima data especial.",
    "Diversão simples também pode virar lembrança boa.",
    "Para completar o cantinho de brincar, fica a dica.",
    "Essa combina com tardes mais leves e cheias de imaginação.",
    "Um presente pensado com carinho sempre chama atenção.",
    "Boa opção para quem quer fugir do presente repetido.",
    "A brincadeira ganha outro clima quando chega novidade.",
    "Para quem gosta de ver criança se divertindo, vale olhar.",
    "Uma escolha que pode entrar fácil na lista de presentes.",
    "Tem achado bom para deixar a brincadeira mais animada."
  ]),
  ...frasesCuradasV21("calcados", "calcados", [
    "👟 Boa para renovar os passos.",
    "Conforto entra na rotina quando o par acompanha bem.",
    "Para sair com mais estilo e conforto, vale conferir.",
    "Visual começa pelos pés.",
    "Par novo no radar para variar os looks da semana.",
    "Vale olhar se o dia pede um calçado mais versátil.",
    "A rotina pede um calçado certo para cada momento.",
    "Os passos do dia agradecem quando o conforto aparece.",
    "Para quem anda bastante, escolher bem faz diferença.",
    "Um par versátil pode acompanhar várias combinações.",
    "Tem calçado que resolve bem a rotina sem esforço.",
    "Para renovar o visual de baixo para cima, vale conferir.",
    "Quem gosta de praticidade sabe que calçado conta muito.",
    "Boa opção para deixar pronta na saída de casa.",
    "Uma escolha dessas pode entrar fácil no uso diário.",
    "Vale colocar no radar para variar os looks da semana.",
    "Entre conforto e estilo, essa merece uma olhada.",
    "Para quem procura um par coringa, fica a dica.",
    "A rotina fora de casa pede escolhas bem pensadas.",
    "Um calçado novo sempre muda a leitura do visual.",
    "Pode ser aquele par que faltava para completar combinações.",
    "Boa para quem quer praticidade sem perder estilo.",
    "Tem novidade boa para quem vive de agenda cheia.",
    "Para caminhar, trabalhar ou sair, vale conferir.",
    "Um par certo deixa o dia mais fácil de encarar."
  ]),
  ...frasesCuradasV21("casa", "casa", [
    "🏠 Boa para cuidar da casa.",
    "Rotina da casa mais prática.",
    "Cada canto da casa merece atenção.",
    "Um detalhe simples pode deixar a casa mais funcional.",
    "A casa organizada ajuda muito.",
    "Para quem curte praticidade em casa, vale uma olhada.",
    "Para dias corridos, praticidade em casa faz diferença.",
    "Uma casa mais funcional começa por escolhas simples.",
    "Tem coisa que deixa a rotina da casa mais simples.",
    "Uma novidade para quem gosta de arrumar a casa.",
    "Uma casa prática começa com escolhas que fazem sentido.",
    "Para deixar a casa mais funcional, vale conferir.",
    "Quem gosta de casa organizada sabe valorizar bons achados.",
    "Pode ser aquele detalhe que faltava em casa.",
    "Uma opção útil para renovar a casa sem mudar tudo.",
    "Vale colocar no radar para facilitar tarefas da casa.",
    "A rotina da casa fica melhor com soluções simples.",
    "Para quem cuida da casa com carinho, essa merece atenção.",
    "Um item certo pode deixar a casa mais agradável.",
    "Boa escolha para quem gosta de praticidade em casa.",
    "Tem novidade boa para deixar a casa mais pronta.",
    "Para organizar a casa, decorar ou facilitar, vale uma olhada.",
    "Casa bonita também pode ser casa fácil de cuidar.",
    "Uma solução simples pode mudar a rotina da casa.",
    "Esse tipo de achado combina com casa bem cuidada."
  ]),
  ...frasesCuradasV21("casa_eletro", "casa_eletro", [
    "🏠 Boa para tarefas da casa.",
    "Praticidade na rotina doméstica vale muito nos dias corridos.",
    "Um eletro útil pode mudar pequenas tarefas da casa.",
    "Para deixar tarefas menos demoradas, vale conferir.",
    "Tarefa simples fica melhor quando a rotina ajuda.",
    "Vale olhar se a ideia é facilitar o dia em casa.",
    "Casa funcionando melhor deixa a rotina mais tranquila.",
    "Rotina doméstica no radar para quem quer ganhar tempo.",
    "Um eletro certo pode poupar tempo em tarefas chatas.",
    "Para quem gosta de praticidade em casa, vale conferir.",
    "Tem equipamento que ajuda a deixar a rotina mais leve.",
    "Uma novidade dessas conversa com cozinha, limpeza e organização.",
    "Boa opção para quem quer agilizar o dia a dia.",
    "Eletrodoméstico bem escolhido vira aliado da semana.",
    "Vale colocar no radar se a casa anda corrida.",
    "Para facilitar tarefas repetidas, essa merece atenção.",
    "Quem cuida da casa sabe como praticidade ajuda.",
    "Uma escolha funcional pode melhorar bastante a rotina doméstica.",
    "Tem item que resolve pequenas tarefas sem drama.",
    "Para deixar tudo mais simples em casa, fica a dica.",
    "A rotina agradece quando o trabalho fica mais leve.",
    "Boa para quem quer casa prática sem complicação.",
    "Um aliado desses pode entrar fácil no dia a dia.",
    "Vale conferir se a ideia é ganhar tempo em casa.",
    "Pequenos atalhos domésticos fazem diferença na semana."
  ]),
  ...frasesCuradasV21("celulares", "celulares", [
    "📱 Boa para trocar de celular.",
    "Quem passa o dia conectado sabe valorizar um aparelho melhor.",
    "Celular novo no radar para quem pensa em renovar.",
    "Para quem usa o celular o dia inteiro, vale conferir.",
    "Um upgrade útil pode deixar a rotina mais conectada.",
    "Vale olhar o aparelho com calma antes de decidir.",
    "Tecnologia certa acompanha melhor a rotina conectada.",
    "Conexão melhor muda bastante o uso no dia a dia.",
    "Para quem vive conectado, essa merece uma olhada.",
    "Seu próximo celular pode aparecer quando menos se espera.",
    "Uma novidade dessas conversa com quem usa o aparelho o dia inteiro.",
    "Trocar de celular fica mais interessante com uma boa oportunidade.",
    "Para renovar o aparelho sem pressa, vale conferir.",
    "Quem depende do celular na rotina sabe como escolha importa.",
    "Pode ser uma boa para atualizar a vida conectada.",
    "Celular certo acompanha trabalho, conversa, foto e descanso.",
    "Tem novidade boa para quem estava pensando em trocar.",
    "Uma opção para deixar o dia mais conectado e prático.",
    "Vale colocar no radar antes de decidir o próximo aparelho.",
    "Para quem procura tecnologia no bolso, fica a dica.",
    "Um upgrade no celular sempre chama atenção na hora certa.",
    "Boa alternativa para quem quer renovar o aparelho.",
    "A rotina digital fica melhor quando o celular acompanha.",
    "Essa pode fazer sentido para quem usa tudo pelo telefone.",
    "Entre mensagens, fotos e apps, vale olhar com calma."
  ]),
  ...frasesCuradasV21("climatizacao", "climatizacao", [
    "🌬️ Boa para refrescar o ambiente.",
    "Conforto térmico entra na conta.",
    "Para enfrentar dias quentes com mais conforto, vale conferir.",
    "Ambiente mais agradável entra no radar quando o calor aperta.",
    "O clima da casa merece atenção antes dos dias pesados.",
    "Vale olhar antes do calor virar problema na rotina.",
    "Casa mais confortável ajuda muito nos dias abafados.",
    "Rotina fresca faz diferença quando o ambiente colabora.",
    "Para deixar o ambiente mais agradável, vale conferir.",
    "Tem dia em que cuidar do clima da casa vira prioridade.",
    "Uma solução dessas pode ajudar nos dias mais abafados.",
    "Quem sofre com calor sabe que conforto muda a rotina.",
    "Boa opção para preparar a casa antes da próxima onda quente.",
    "Para circular melhor o ar, essa merece entrar no radar.",
    "Um ambiente mais confortável deixa tudo mais leve.",
    "Vale colocar na lista de quem quer se preparar melhor.",
    "Climatização certa ajuda bastante na rotina de casa.",
    "Para quarto, sala ou escritório, vale uma olhada.",
    "Tem novidade boa para quem quer mais conforto no ambiente.",
    "Uma escolha prática para atravessar dias quentes com calma.",
    "Boa para quem quer melhorar o clima sem complicar.",
    "Cuidar do ar da casa também é cuidar da rotina.",
    "Quando o calor aperta, esse tipo de item chama atenção.",
    "Para deixar o cantinho mais agradável, fica a dica.",
    "Conforto em casa começa por um ambiente mais equilibrado."
  ]),
  ...frasesCuradasV21("computadores", "computadores", [
    "💻 Boa para atualizar a estação.",
    "Produtividade também depende de uma máquina que acompanhe.",
    "Para trabalhar com mais fluidez, vale conferir.",
    "Setup de trabalho no radar para organizar melhor a rotina.",
    "Computador certo ajuda muito quando tarefa não espera.",
    "Vale olhar se estudo e trabalho pedem mais fôlego.",
    "Rotina produtiva fica mais leve com tecnologia certa.",
    "Um upgrade para a mesa pode mudar o ritmo do dia.",
    "Para quem trabalha ou estuda no computador, vale conferir.",
    "Uma máquina mais adequada pode deixar a rotina mais fluida.",
    "Quem passa horas na tela sabe como escolha pesa.",
    "Tem novidade boa para atualizar a estação sem pressa.",
    "Boa opção para deixar estudos e tarefas mais organizados.",
    "Para montar um cantinho produtivo, essa merece atenção.",
    "Computador certo acompanha reunião, estudo e projeto.",
    "Vale colocar no radar se a rotina pede mais fôlego.",
    "Uma escolha dessas pode ajudar no dia a dia digital.",
    "Para quem vive entre arquivos e abas, fica a dica.",
    "A mesa de trabalho ganha outra cara com um bom upgrade.",
    "Pode ser uma alternativa interessante para renovar a máquina.",
    "Produtividade começa quando a ferramenta acompanha o ritmo.",
    "Boa para quem quer estudar, trabalhar e organizar melhor.",
    "Tem item que conversa bem com rotina de home office.",
    "Para atualizar o setup sem exagero, vale uma olhada.",
    "Entre estudo e trabalho, essa pode fazer sentido."
  ]),
  ...frasesCuradasV21("cozinha_pratica", "cozinha_pratica", [
    "🍳 Boa para agilizar a cozinha.",
    "Preparo mais prático ajuda quando a rotina aperta.",
    "Cozinha organizada rende mais na hora de preparar tudo.",
    "Para cozinhar com menos improviso, vale conferir.",
    "A receita do dia agradece quando a bancada ajuda.",
    "Vale olhar antes da próxima receita sair do papel.",
    "Rotina da cozinha mais leve.",
    "Um aliado útil na bancada pode poupar etapas.",
    "Para quem cozinha sempre, praticidade faz diferença.",
    "Uma novidade dessas pode deixar o preparo menos corrido.",
    "Tem item que vira aliado na hora de fazer comida.",
    "Boa opção para organizar melhor a rotina da cozinha.",
    "Quem gosta de receita prática sabe valorizar bons utensílios.",
    "Para deixar a bancada mais funcional, vale conferir.",
    "Cozinha prática combina com itens simples e bem escolhidos.",
    "Vale colocar no radar antes da próxima receita.",
    "Um aliado certo pode deixar o preparo mais tranquilo.",
    "Para café, almoço ou jantar, essa pode ajudar.",
    "A rotina na cozinha fica melhor quando tudo está à mão.",
    "Boa para quem quer ganhar tempo sem bagunçar tudo.",
    "Tem novidade boa para quem gosta de preparar em casa.",
    "Um detalhe certo facilita muito a vida na cozinha.",
    "Para quem vive testando receita, fica a dica.",
    "Cozinhar com praticidade deixa o dia menos pesado.",
    "Essa pode entrar fácil no canto mais usado da casa."
  ]),
  ...frasesCuradasV21("eletronicos", "eletronicos", [
    "⚡ Tecnologia útil para o dia.",
    "Eletrônico novo no radar para quem gosta de tecnologia.",
    "Tecnologia no dia a dia fica melhor quando é prática.",
    "Para modernizar a rotina sem complicar, vale conferir.",
    "Conectividade também ajuda quando tudo precisa funcionar junto.",
    "Vale conferir se a tecnologia conversa com sua rotina.",
    "O dia a dia fica mais esperto com o item certo.",
    "Novidade tecnológica por aqui para quem gosta de atualizar.",
    "Para quem gosta de tecnologia, essa merece atenção.",
    "Um eletrônico certo pode facilitar muita coisa na rotina.",
    "Tem dispositivo que entra fácil no uso do dia a dia.",
    "Boa opção para deixar a casa ou mesa mais conectada.",
    "Quem acompanha novidades digitais sabe quando algo chama atenção.",
    "Para modernizar pequenos momentos, vale conferir.",
    "Uma escolha prática pode simplificar tarefas comuns.",
    "Vale colocar no radar se tecnologia faz parte do seu dia.",
    "Entre cabos, telas e acessórios, essa pode ajudar.",
    "A rotina digital fica melhor com itens bem pensados.",
    "Tem novidade boa para quem gosta de soluções práticas.",
    "Para organizar melhor o uso da tecnologia, fica a dica.",
    "Um detalhe eletrônico pode deixar tudo mais funcional.",
    "Boa alternativa para quem quer atualizar a rotina.",
    "Pode ser aquele item que resolve uma necessidade simples.",
    "Para quem usa tecnologia todos os dias, vale uma olhada.",
    "Essa conversa bem com uma vida mais conectada."
  ]),
  ...frasesCuradasV21("esporte", "esporte", [
    "🏃 Boa para manter o ritmo.",
    "Treino em dia pede apoio para manter o ritmo.",
    "Rotina ativa no radar para quem gosta de se mexer.",
    "Para deixar o treino mais organizado, vale conferir.",
    "O movimento do dia agradece quando o preparo acompanha.",
    "Vale olhar se esporte faz parte da sua rotina.",
    "Energia para a rotina começa em escolhas mais práticas.",
    "Boa para sair do sofá.",
    "Para quem treina com frequência, essa merece atenção.",
    "Uma novidade dessas pode acompanhar melhor a rotina ativa.",
    "Quem gosta de se movimentar sabe que detalhe ajuda.",
    "Boa opção para deixar o treino mais organizado.",
    "Para preparar a próxima atividade, vale conferir.",
    "Esporte combina com escolhas que acompanham o ritmo.",
    "Vale colocar no radar antes do próximo treino.",
    "Um item certo pode deixar a prática mais confortável.",
    "Para caminhada, academia ou rotina ativa, fica a dica.",
    "Tem novidade boa para quem gosta de manter constância.",
    "A rotina de treino fica melhor com apoio certo.",
    "Boa para quem quer movimento sem complicar demais.",
    "Pode ser uma escolha útil para acompanhar a semana.",
    "Para quem cuida do corpo no dia a dia, vale olhar.",
    "Rotina ativa também precisa de praticidade.",
    "Um bom achado pode ajudar a manter o plano em pé.",
    "Entre treino e descanso, essa pode fazer sentido."
  ]),
  ...frasesCuradasV21("ferramentas", "ferramentas", [
    "🛠️ Boa para completar a caixa.",
    "Ferramenta certa ajuda muito.",
    "Projeto novo no radar para quem gosta de colocar a mão na massa.",
    "Para manutenção sem depender de improviso, vale conferir.",
    "Tarefa em casa fica mais prática com a ferramenta certa.",
    "Vale olhar para deixar a oficina mais preparada.",
    "Caixa pronta evita procura na hora do reparo.",
    "Boa para resolver tarefas que sempre ficam pendentes.",
    "Para quem gosta de consertar tudo, vale conferir.",
    "Uma ferramenta certa pode salvar tempo no fim de semana.",
    "Tem item que faz falta justamente na hora do aperto.",
    "Boa opção para deixar a caixa mais completa.",
    "Quem vive inventando projeto sabe como ferramenta ajuda.",
    "Para manutenção simples em casa, essa merece atenção.",
    "Vale colocar no radar antes do próximo reparo.",
    "Um acessório útil pode facilitar bastante a tarefa.",
    "Para montar, ajustar ou consertar, fica a dica.",
    "A rotina de pequenos reparos fica mais tranquila.",
    "Tem novidade boa para quem gosta de deixar tudo pronto.",
    "Boa para quem prefere resolver sem depender de improviso.",
    "Uma escolha prática para projetos de casa e oficina.",
    "Ferramenta bem escolhida vira companheira por muito tempo.",
    "Para o próximo ajuste, essa pode fazer sentido.",
    "Quem organiza a caixa sabe o valor de um item útil.",
    "Um detalhe certo pode destravar aquela tarefa pendente."
  ]),
  ...frasesCuradasV21("gamer", "gamer", [
    "🎮 Boa para ajustar o setup.",
    "Setup gamer merece atenção de quem joga com frequência.",
    "Um upgrade para deixar a jogatina mais confortável.",
    "Para deixar o setup mais completo, vale conferir.",
    "Setup para jogar entra no radar quando falta aquele ajuste.",
    "Boa para completar o setup.",
    "Setup mais preparado deixa a jogatina fluir melhor.",
    "🕹️ Novidade para melhorar o setup.",
    "Para quem gosta de jogar, esse upgrade merece radar.",
    "Seu setup sempre tem espaço para um upgrade interessante.",
    "Uma novidade dessas pode deixar o setup mais divertido.",
    "Quem joga sabe que detalhe no setup faz diferença.",
    "Boa opção para deixar o setup pronto para a próxima partida.",
    "Para atualizar o setup gamer, vale conferir.",
    "Tem item que combina com setup, gameplay e diversão.",
    "Vale colocar no radar se o setup anda pedindo atenção.",
    "A hora de jogar fica melhor com o setup no lugar.",
    "Para quem vive de partida online, upgrade no radar.",
    "Um upgrade certo pode mudar o clima do setup.",
    "Boa para quem quer deixar o setup mais confortável.",
    "Entre teclado, tela e cadeira, o setup conta.",
    "Tem upgrade bom para quem acompanha o mundo gamer.",
    "Para montar ou melhorar o setup, vale uma olhada.",
    "A diversão ganha outro ritmo quando o setup ajuda.",
    "Essa conversa com quem leva o setup a sério."
  ]),
  ...frasesCuradasV21("games", "games", [
    "🕹️ Boa para a próxima partida.",
    "Jogo novo no radar para variar a próxima partida.",
    "Diversão também pede novidade quando a coleção para.",
    "Para quem quer descobrir outra aventura, vale conferir.",
    "Tempo livre agradece quando aparece um jogo interessante.",
    "Vale olhar se a próxima jogatina pede novidade.",
    "Partida no sofá pode ficar mais divertida com escolha certa.",
    "Boa para variar a coleção.",
    "Para quem curte games, essa merece uma olhada.",
    "Uma novidade dessas pode render boas horas de diversão.",
    "Quem gosta de jogar sempre encontra espaço para mais um título.",
    "Boa opção para movimentar a biblioteca de jogos.",
    "Para variar a próxima sessão, vale conferir.",
    "Tem jogo que combina com fim de semana tranquilo.",
    "Vale colocar no radar antes da próxima maratona.",
    "Um título novo pode mudar o clima da jogatina.",
    "Para jogar sozinho ou com a turma, fica a dica.",
    "A coleção ganha vida quando aparece algo diferente.",
    "Tem novidade boa para quem acompanha games e consoles.",
    "Boa para quem gosta de descobrir outra aventura.",
    "Pode ser aquele jogo para deixar separado na lista.",
    "Entre campanha, desafio e diversão, vale olhar com calma.",
    "Quem joga no console sabe como novidade anima.",
    "Uma escolha legal para renovar o tempo de jogar.",
    "Essa pode entrar na rotação da próxima partida."
  ]),
  ...frasesCuradasV21("iluminacao", "iluminacao", [
    "💡 Boa para melhorar o ambiente.",
    "Luz certa muda o espaço.",
    "Iluminação também decora quando combina com o ambiente.",
    "Para deixar a casa mais iluminada, vale conferir.",
    "Ambiente mais aconchegante começa pela luz certa.",
    "Vale olhar se algum canto precisa de mais luz.",
    "Projeto da casa no radar para renovar o ambiente.",
    "Um detalhe de luz pode mudar a sensação do espaço.",
    "Para quem gosta de ambiente bem pensado, vale conferir.",
    "Uma iluminação certa pode mudar a sensação de um cômodo.",
    "Tem detalhe de luz que deixa a casa mais agradável.",
    "Boa opção para renovar sem mexer em tudo.",
    "Para ajustar aquele canto da casa, essa merece atenção.",
    "Quem cuida da decoração sabe que luz faz diferença.",
    "Vale colocar no radar para o próximo projeto.",
    "Um ponto de iluminação pode deixar tudo mais funcional.",
    "Para sala, quarto ou bancada, fica a dica.",
    "A casa ganha outro clima quando a luz acompanha.",
    "Tem novidade boa para quem gosta de ambientes acolhedores.",
    "Boa para deixar o espaço mais bonito e prático.",
    "Pode ser aquele toque que faltava no cantinho.",
    "Iluminar bem também ajuda a organizar melhor o dia.",
    "Para quem pensa em renovar o ambiente, vale olhar.",
    "Um item simples pode mudar bastante o visual da casa.",
    "Essa combina com projeto pequeno e resultado visível."
  ]),
  ...frasesCuradasV21("infantil", "infantil", [
    "🧸 Boa para os pequenos.",
    "Rotina infantil fica mais prática com escolhas bem pensadas.",
    "Para criança usar no dia a dia, vale conferir.",
    "Visual infantil no radar para renovar sem exagero.",
    "O dia dos pequenos agradece quando a rotina fica leve.",
    "Vale olhar com carinho antes da próxima troca.",
    "Peça infantil bem pensada acompanha melhor a rotina.",
    "Boa para renovar a rotina.",
    "Para quem procura algo infantil, vale conferir.",
    "Uma escolha prática pode ajudar bastante no dia a dia.",
    "Tem novidade que combina com criança em movimento.",
    "Boa opção para renovar sem complicar a rotina.",
    "Para deixar tudo pronto para os pequenos, fica a dica.",
    "Quem cuida de criança sabe que praticidade conta.",
    "Vale colocar no radar antes da próxima troca.",
    "Uma peça útil pode acompanhar bem a fase dos pequenos.",
    "Para brincar, sair ou ficar em casa, vale olhar.",
    "A rotina infantil pede escolhas confortáveis e simples.",
    "Tem achado bom para completar o guarda-roupa dos pequenos.",
    "Boa para quem gosta de deixar opções separadas.",
    "Pode ser uma alternativa interessante para presentear criança.",
    "Para acompanhar o crescimento, essa merece atenção.",
    "Pequenos detalhes deixam a rotina mais fácil.",
    "Uma novidade assim pode resolver a próxima saída.",
    "Essa conversa com o dia a dia de quem tem pequenos."
  ]),
  ...frasesCuradasV21("limpeza", "limpeza", [
    "🧹 Boa para deixar em ordem.",
    "Faxina mais prática ajuda quando a semana está corrida.",
    "Limpeza no radar da casa para manter tudo em ordem.",
    "Para organizar a rotina de limpeza, vale conferir.",
    "Rotina limpa sem drama começa com soluções simples.",
    "Vale olhar antes da próxima faxina da casa.",
    "Casa em ordem agradece quando a limpeza fica prática.",
    "Uma ajuda simples na limpeza pode economizar esforço.",
    "Para quem gosta de casa organizada, vale conferir.",
    "Tem item que deixa a limpeza menos cansativa.",
    "Uma novidade dessas pode facilitar bastante a faxina.",
    "Boa opção para manter tudo em ordem na semana.",
    "Quem cuida da casa sabe que limpeza pede praticidade.",
    "Para deixar o cuidado mais rápido, essa merece atenção.",
    "Vale colocar no radar antes da próxima faxina.",
    "Um aliado certo pode simplificar tarefas repetidas.",
    "Para limpar, organizar e seguir o dia, fica a dica.",
    "A rotina fica mais leve quando a casa está em ordem.",
    "Tem produto útil para quem gosta de praticidade.",
    "Boa para quem quer menos esforço na limpeza diária.",
    "Pode ser aquele item que resolve uma parte chata.",
    "Para manter a casa pronta, vale dar uma olhada.",
    "Limpeza simples também depende de boas escolhas.",
    "Uma ajuda dessas pode economizar tempo na rotina.",
    "Essa combina com quem prefere tudo no lugar."
  ]),
  ...frasesCuradasV21("mercado", "mercado", [
    "🛒 Boa para repor a despensa.",
    "A lista da casa fica mais completa com escolhas úteis.",
    "Mercado da semana no radar para organizar a despensa.",
    "Para abastecer antes de faltar, vale conferir.",
    "Despensa pronta ajuda muito nos dias corridos.",
    "Vale olhar para repor o básico da casa.",
    "Compra da casa mais prática.",
    "Boa para deixar reservado e evitar compra de última hora.",
    "Para quem organiza a compra do mês, vale conferir.",
    "Tem item que sempre encontra espaço na despensa.",
    "Uma escolha dessas ajuda a manter a casa abastecida.",
    "Boa opção para entrar na lista antes de faltar.",
    "Quem faz mercado sabe como planejamento facilita.",
    "Para completar a próxima compra, essa merece atenção.",
    "Vale colocar no radar antes de fechar a lista.",
    "Um item útil pode resolver a rotina da semana.",
    "Para abastecer sem pressa, fica a dica.",
    "A despensa organizada deixa o dia a dia mais simples.",
    "Tem novidade boa para quem cuida das compras da casa.",
    "Boa para quem gosta de deixar o básico preparado.",
    "Pode ser uma adição útil para a próxima ida ao mercado.",
    "Lista de mercado fica melhor com escolha certeira.",
    "Para repor com calma, vale dar uma olhada.",
    "Um achado simples pode facilitar a rotina da casa.",
    "Essa conversa com quem gosta de compra bem planejada."
  ]),
  ...frasesCuradasV21("moda", "moda", [
    "✨ Boa para renovar o visual.",
    "Guarda-roupa pede novidade quando as combinações repetem.",
    "Para combinar com peças que você já usa, vale conferir.",
    "Visual do dia no radar para quem gosta de variar.",
    "Peça versátil ajuda muito na hora de montar o look.",
    "Vale olhar para variar o visual sem complicação.",
    "Estilo sem complicar combina com rotina de verdade.",
    "Um detalhe novo no look pode mudar a combinação.",
    "Uma peça nova pode mudar o clima do visual.",
    "Para quem gosta de variar combinações, vale conferir.",
    "Conforto e estilo no dia a dia sempre ajudam.",
    "Uma escolha versátil rende várias combinações no guarda-roupa.",
    "Boa opção para renovar sem trocar tudo de uma vez.",
    "Quem gosta de moda sabe quando uma peça chama atenção.",
    "Para atualizar o look da semana, essa merece uma olhada.",
    "Tem novidade boa para quem acompanha estilo de perto.",
    "Uma peça coringa pode resolver mais de uma saída.",
    "Vale colocar no radar antes da próxima combinação.",
    "Para o trabalho, passeio ou rotina, fica a dica.",
    "O visual ganha outro ar com uma escolha bem pensada.",
    "Boa para quem procura algo fácil de combinar.",
    "Pequenos detalhes deixam o guarda-roupa mais interessante.",
    "Uma novidade dessas pode entrar fácil no uso diário.",
    "Para quem gosta de se vestir bem sem esforço, vale olhar.",
    "Essa conversa com estilo prático e rotina real."
  ]),
  ...frasesCuradasV21("oportunidade", "oportunidade", [
    "👀 Vale dar uma olhada.",
    "Essa chamou atenção por aqui.",
    "Boa para colocar no radar e decidir com calma.",
    "Vale conferir antes de seguir para a próxima opção.",
    "Pode fazer sentido agora para quem gosta de garimpar.",
    "Vale olhar com calma para entender se combina com você.",
    "Achado simples no radar para quem gosta de novidade.",
    "Essa merece alguns segundos antes de passar batido.",
    "Tem novidade por aqui que vale conferir.",
    "Uma descoberta dessas merece um pouco de atenção.",
    "Pode ser uma boa opção para avaliar sem pressa.",
    "Essa apareceu no radar e vale uma conferida.",
    "Para quem gosta de bons achados, fica a dica.",
    "Vale guardar essa opção para olhar melhor depois.",
    "Uma oportunidade neutra para analisar com calma.",
    "Tem coisa interessante passando por aqui.",
    "Boa sugestão para quem está garimpando novidades.",
    "Essa pode entrar na lista de opções para avaliar.",
    "Vale conferir antes de seguir para a próxima.",
    "Um achado desses pede uma olhada rápida.",
    "Pode ser exatamente o tipo de opção que chama atenção.",
    "Essa ficou interessante o bastante para entrar no radar.",
    "Vale abrir e decidir com calma.",
    "Tem algo aqui que merece ser visto.",
    "Uma opção discreta, mas boa de colocar na lista."
  ], ["oportunidade"]),
  ...frasesCuradasV21("perifericos", "perifericos", [
    "🖥️ Boa para completar a mesa.",
    "Setup mais organizado ajuda na rotina de trabalho e jogo.",
    "O acessório certo faz diferença quando a mesa vive cheia.",
    "Para deixar a estação mais funcional, vale conferir.",
    "Mesa equipada no radar para quem usa tudo todo dia.",
    "Vale olhar se o setup anda pedindo um ajuste.",
    "Rotina digital fica mais prática com periféricos certos.",
    "Um detalhe útil na bancada pode melhorar o fluxo.",
    "Para quem usa computador todo dia, periférico conta muito.",
    "Um acessório certo pode deixar a mesa mais confortável.",
    "Tem detalhe de setup que melhora bastante a rotina.",
    "Boa opção para organizar melhor a estação de trabalho.",
    "Quem passa horas na mesa sabe valorizar bons acessórios.",
    "Para atualizar o canto do computador, vale conferir.",
    "Vale colocar no radar se o setup anda pedindo ajuste.",
    "Um periférico útil pode facilitar tarefas repetidas.",
    "Para trabalhar, estudar ou jogar, fica a dica.",
    "A mesa fica mais pronta quando os detalhes acompanham.",
    "Tem novidade boa para quem gosta de setup bem montado.",
    "Boa para quem quer praticidade sem ocupar espaço demais.",
    "Pode ser aquele ajuste pequeno que muda o uso diário.",
    "Para deixar cabos, comandos ou tarefas mais simples.",
    "Um acessório bem escolhido acompanha muita rotina.",
    "Entre notebook, monitor e mesa, vale olhar com calma.",
    "Essa conversa com quem gosta de tudo no lugar."
  ]),
  ...frasesCuradasV21("pesca_camping", "pesca_camping", [
    "🎣 Boa para o ar livre.",
    "Aventura no radar para quem gosta de sair preparado.",
    "Camping pede preparo antes de colocar o pé na estrada.",
    "Para pescaria, acampamento ou passeio, vale conferir.",
    "Passeio mais organizado ajuda a aproveitar melhor o dia.",
    "Vale olhar antes de sair para a próxima aventura.",
    "Natureza combina com preparo e itens bem escolhidos.",
    "Item útil para camping costuma facilitar bastante fora de casa.",
    "Para quem curte pesca ou camping, vale conferir.",
    "Uma escolha prática pode ajudar no próximo passeio.",
    "Quem vai para o ar livre sabe que preparo conta.",
    "Boa opção para deixar separada antes da viagem.",
    "Tem item que facilita bastante fora de casa.",
    "Para organizar melhor a aventura, essa merece atenção.",
    "Vale colocar no radar antes da próxima pescaria.",
    "Um acessório certo pode evitar improviso no passeio.",
    "Para trilha, camping ou beira d'água, fica a dica.",
    "A experiência ao ar livre fica melhor com tudo pronto.",
    "Tem novidade boa para quem gosta de sair da rotina.",
    "Boa para quem prefere chegar preparado no destino.",
    "Pode ser aquele item que falta na mochila.",
    "Para curtir o fim de semana fora, vale uma olhada.",
    "Pesca e camping combinam com escolha funcional.",
    "Um achado simples pode ajudar bastante no acampamento.",
    "Essa conversa com quem gosta de aventura sem bagunça."
  ]),
  ...frasesCuradasV21("pet", "pet", [
    "🐾 Boa para rotina pet.",
    "Cuidado diário sempre conta na rotina de quem tem pet.",
    "Novidade pet no radar para incluir nos cuidados da rotina.",
    "Para cuidar melhor no dia a dia, vale conferir.",
    "Rotina do pet fica mais prática com escolhas úteis.",
    "Vale olhar se o cuidado do pet precisa de algo novo.",
    "Pequenos cuidados fazem diferença no bem-estar da rotina.",
    "Boa para ter em casa quando o assunto é cuidado pet.",
    "Quem tem pet sabe como a rotina pede cuidado.",
    "Uma novidade dessas pode ajudar no dia a dia do pet.",
    "Para deixar os cuidados mais práticos, vale conferir.",
    "Tem item que facilita bastante a vida de quem cuida.",
    "Boa opção para manter tudo mais organizado em casa.",
    "Pet bem cuidado começa em pequenos hábitos.",
    "Vale colocar no radar antes de repor a rotina.",
    "Um cuidado simples pode deixar o dia mais tranquilo.",
    "Para passeio, higiene ou alimentação, fica a dica.",
    "A rotina com pet fica melhor quando tudo está preparado.",
    "Tem novidade boa para incluir nos cuidados da semana.",
    "Boa para quem gosta de deixar o cantinho pet em ordem.",
    "Pode ser uma escolha útil para acompanhar a rotina.",
    "Para quem cuida com carinho, vale dar uma olhada.",
    "Pequenas ajudas fazem parte da vida com pet.",
    "Uma opção prática pode deixar o dia a dia mais tranquilo.",
    "Essa conversa com quem tem pet em casa."
  ])
]);

const BANCO_ASSOCIATIVO_V2 = Object.freeze([
  ...BANCO_ASSOCIATIVO_V2_BASE,
  ...EXPANSAO_HUMANA_V21
]);

module.exports = {
  BANCO_ASSOCIATIVO_V2,
  BANCO_ASSOCIATIVO_V2_BASE,
  EXPANSAO_HUMANA_V21
};
