-- Local candidate for the authoritative post-epoch queue. Apply only after
-- the operation-state migration and an explicit, reviewed cutover preflight.
-- This script creates no legacy/VIVA dependency and never deletes old data.
CREATE TABLE IF NOT EXISTS engine_universal_queue_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_epoch_started_at timestamptz NOT NULL,
  workspace_id text NOT NULL CHECK (btrim(workspace_id) <> ''),
  evento_id bigint NOT NULL REFERENCES engine_eventos_brutos(id),
  job_id bigint NOT NULL REFERENCES engine_jobs_cliente(id),
  oferta_id bigint NOT NULL REFERENCES engine_ofertas(id),
  origem_fluxo text NOT NULL CHECK (btrim(origem_fluxo) <> ''),
  capturado_em timestamptz NOT NULL,
  item_payload jsonb NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN
    ('pending','partial','sent','not_sent','error','no_opportunity')),
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  terminal_at timestamptz,
  UNIQUE (id, operation_epoch_started_at, workspace_id),
  UNIQUE (operation_epoch_started_at, workspace_id, oferta_id),
  CHECK (capturado_em >= operation_epoch_started_at),
  CHECK ((status IN ('sent','not_sent','error','no_opportunity')
      AND terminal_at IS NOT NULL) OR
    (status = 'pending' AND terminal_at IS NULL) OR
    status = 'partial')
);

CREATE INDEX IF NOT EXISTS engine_uq_items_open_workspace_idx
  ON engine_universal_queue_items
    (operation_epoch_started_at, workspace_id, id)
  WHERE terminal_at IS NULL;
CREATE INDEX IF NOT EXISTS engine_uq_items_social_workspace_idx
  ON engine_universal_queue_items
    (operation_epoch_started_at, workspace_id, id DESC);
CREATE INDEX IF NOT EXISTS engine_uq_items_terminal_history_idx
  ON engine_universal_queue_items
    (operation_epoch_started_at, workspace_id, terminal_at DESC, id DESC)
  WHERE terminal_at IS NOT NULL;

-- One stable commercial dispatch per item/destination. The target snapshot
-- and owner are inserted in the same transaction as the queue item. The
-- reservation is bound later, immediately before the first transport.
CREATE TABLE IF NOT EXISTS engine_universal_fanout_owners (
  owner_id text PRIMARY KEY CHECK (owner_id ~ '^[0-9a-f]{64}$'),
  queue_item_id bigint NOT NULL,
  operation_epoch_started_at timestamptz NOT NULL,
  workspace_id text NOT NULL CHECK (btrim(workspace_id) <> ''),
  destination_id text NOT NULL CHECK (btrim(destination_id) <> ''),
  target_snapshot_hash text NOT NULL CHECK (target_snapshot_hash ~ '^[0-9a-f]{64}$'),
  commercial_reservation_key text,
  reservation_token uuid,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY (queue_item_id,operation_epoch_started_at,workspace_id)
    REFERENCES engine_universal_queue_items
      (id,operation_epoch_started_at,workspace_id),
  UNIQUE (queue_item_id,operation_epoch_started_at,workspace_id,destination_id),
  UNIQUE (owner_id,queue_item_id,operation_epoch_started_at,workspace_id,destination_id),
  CHECK ((commercial_reservation_key IS NULL) = (reservation_token IS NULL))
);

CREATE TABLE IF NOT EXISTS engine_universal_queue_destinations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  queue_item_id bigint NOT NULL,
  operation_epoch_started_at timestamptz NOT NULL,
  workspace_id text NOT NULL CHECK (btrim(workspace_id) <> ''),
  destination_id text NOT NULL CHECK (btrim(destination_id) <> ''),
  fanout_owner_id text NOT NULL,
  target_key text NOT NULL CHECK (btrim(target_key) <> ''),
  connection_id text,
  channel text NOT NULL CHECK (channel IN ('whatsapp','telegram','discord')),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN
    ('pending','claimed','send_started','sent','skipped','failed','ambiguous')),
  available_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  lease_token uuid,
  lease_until timestamptz,
  send_started_at timestamptz,
  confirmation_key text,
  provider_message_id text,
  confirmed_at timestamptz,
  commercial_cta jsonb,
  credit_debited boolean,
  terminal_reason text,
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  FOREIGN KEY (queue_item_id, operation_epoch_started_at, workspace_id)
    REFERENCES engine_universal_queue_items
      (id, operation_epoch_started_at, workspace_id),
  CONSTRAINT engine_uq_destination_owner_fk
  FOREIGN KEY (fanout_owner_id,queue_item_id,operation_epoch_started_at,
    workspace_id,destination_id)
    REFERENCES engine_universal_fanout_owners
      (owner_id,queue_item_id,operation_epoch_started_at,workspace_id,destination_id),
  UNIQUE (queue_item_id, destination_id, target_key),
  CHECK (status <> 'sent' OR
    (confirmed_at IS NOT NULL AND confirmation_key IS NOT NULL
      AND btrim(confirmation_key) <> '' AND credit_debited IS NOT NULL)),
  CHECK (status NOT IN ('claimed','send_started') OR
    (lease_token IS NOT NULL AND lease_until IS NOT NULL))
);

-- An earlier local foundation may already have the destination table. Keep
-- migration additive: old rows remain visible but fail closed without an
-- owner; new rows must prove ownership. NOT VALID avoids scanning old rows.
ALTER TABLE engine_universal_queue_destinations
  ADD COLUMN IF NOT EXISTS fanout_owner_id text;
ALTER TABLE engine_universal_queue_destinations
  ADD COLUMN IF NOT EXISTS commercial_cta jsonb;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
    WHERE conrelid='engine_universal_queue_destinations'::regclass
      AND conname='engine_uq_destination_owner_present') THEN
    ALTER TABLE engine_universal_queue_destinations
      ADD CONSTRAINT engine_uq_destination_owner_present
      CHECK (fanout_owner_id IS NOT NULL) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
    WHERE conrelid='engine_universal_queue_destinations'::regclass
      AND conname='engine_uq_destination_owner_fk') THEN
    ALTER TABLE engine_universal_queue_destinations
      ADD CONSTRAINT engine_uq_destination_owner_fk
      FOREIGN KEY (fanout_owner_id,queue_item_id,operation_epoch_started_at,
        workspace_id,destination_id)
      REFERENCES engine_universal_fanout_owners
        (owner_id,queue_item_id,operation_epoch_started_at,
         workspace_id,destination_id) NOT VALID;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS engine_uq_dest_open_item_idx
  ON engine_universal_queue_destinations (queue_item_id, status, id)
  WHERE status IN ('pending','claimed','send_started');
CREATE INDEX IF NOT EXISTS engine_uq_dest_workspace_claim_idx
  ON engine_universal_queue_destinations
    (operation_epoch_started_at, workspace_id, status, available_at, id)
  WHERE status IN ('pending','claimed','send_started');
CREATE INDEX IF NOT EXISTS engine_uq_dest_sent_limit_idx
  ON engine_universal_queue_destinations
    (operation_epoch_started_at,workspace_id,destination_id,confirmed_at DESC)
  WHERE status='sent';
-- The destination is the cadence authority. A concurrent worker may not
-- acquire another target of this destination while one send is unresolved.
CREATE UNIQUE INDEX IF NOT EXISTS engine_uq_one_active_destination_idx
  ON engine_universal_queue_destinations
    (operation_epoch_started_at,workspace_id,destination_id)
  WHERE status IN ('claimed','send_started');

-- The send clock belongs to one logical destination in one workspace/epoch.
-- A confirmation advances only that destination; it never advances workspace B
-- or another destination of workspace A.
CREATE TABLE IF NOT EXISTS engine_universal_queue_destination_clock (
  operation_epoch_started_at timestamptz NOT NULL,
  workspace_id text NOT NULL CHECK (btrim(workspace_id) <> ''),
  destination_id text NOT NULL CHECK (btrim(destination_id) <> ''),
  last_confirmed_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (operation_epoch_started_at,workspace_id,destination_id)
);

-- Logical checkpoint/health is per epoch and workspace, never global VIVA.
CREATE TABLE IF NOT EXISTS engine_universal_queue_workspace_state (
  operation_epoch_started_at timestamptz NOT NULL,
  workspace_id text NOT NULL CHECK (btrim(workspace_id) <> ''),
  health text NOT NULL DEFAULT 'UNKNOWN' CHECK (health IN
    ('HEALTHY','RECOVERING','AMBIGUOUS','UNKNOWN')),
  revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0),
  checkpoint_revision bigint NOT NULL DEFAULT 0 CHECK (checkpoint_revision >= 0),
  checked_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (operation_epoch_started_at, workspace_id)
);

-- A retryable post-send projection, not another automatic send queue.
CREATE TABLE IF NOT EXISTS engine_universal_vitrine_outbox (
  operation_epoch_started_at timestamptz NOT NULL,
  queue_item_id bigint NOT NULL,
  workspace_id text NOT NULL,
  state text NOT NULL DEFAULT 'pending'
    CHECK (state IN ('pending','processing','completed','skipped','failed')),
  lease_token uuid,
  lease_until timestamptz,
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  last_result text,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY (operation_epoch_started_at,queue_item_id),
  FOREIGN KEY (queue_item_id,operation_epoch_started_at,workspace_id)
    REFERENCES engine_universal_queue_items
      (id,operation_epoch_started_at,workspace_id)
);
CREATE INDEX IF NOT EXISTS engine_universal_vitrine_outbox_pending_idx
  ON engine_universal_vitrine_outbox
    (operation_epoch_started_at,created_at,queue_item_id)
  WHERE state IN ('pending','processing');
CREATE INDEX IF NOT EXISTS engine_universal_vitrine_outbox_terminal_idx
  ON engine_universal_vitrine_outbox (updated_at,queue_item_id)
  WHERE state IN ('completed','skipped','failed');
